# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
        environment:
          NAMESPACE: damonpetta
          SERVICE: rowi
    working_directory: /go/src/github.com/damonpetta/rowi
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - setup_remote_docker
      - run: docker build -t $NAMESPACE/$SERVICE:$CIRCLE_SHA1 .
      - run: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
      - run: docker tag $NAMESPACE/$SERVICE:$CIRCLE_SHA1 $NAMESPACE/$SERVICE:latest
      - run: docker push $NAMESPACE/$SERVICE
